-- Generated by scripts/mini_projects_seed_sql.py - do not edit by hand.
-- Rebuilds the 20 Python mini projects idempotently.
BEGIN;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-01-bmi-calculator', 'Mini Project 1: BMI Calculator', 'Mini Projects', 'Build your own BMI (Body Mass Index) calculator.

The program reads two lines from input:
Line 1: weight in kilograms (a number, may have decimals)
Line 2: height in centimeters (a number, may have decimals)

BMI formula: BMI = weight / (height_in_meters * height_in_meters)

Print EXACTLY two lines:
Your BMI is: <bmi rounded to 1 decimal place>
Category: <category>

Category rules:
- BMI < 18.5   -> Underweight
- 18.5 to 24.9 -> Normal weight
- 25.0 to 29.9 -> Overweight
- 30.0 or more -> Obese

Example
Input:
70
175
Output:
Your BMI is: 22.9
Category: Normal weight',
     'python', 'main.py', '# BMI Calculator
# Read weight (kg) and height (cm), print BMI and category.
weight = float(input())
# TODO: read height in cm, compute BMI, print the two required lines
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-01-bmi-calculator';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '70
175
', 'Your BMI is: 22.9
Category: Normal weight', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '45
160
', 'Your BMI is: 17.6
Category: Underweight', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '82.5
170
', 'Your BMI is: 28.5
Category: Overweight', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '95
150
', 'Your BMI is: 42.2
Category: Obese', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '61.2
183.5
', 'Your BMI is: 18.2
Category: Underweight', true, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '68.4
165.2
', 'Your BMI is: 25.1
Category: Overweight', true, 6);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-02-interest-calculator', 'Mini Project 2: Simple Interest Calculator', 'Mini Projects', 'Build a Simple Interest calculator for a small finance shop.

Input (three lines):
Line 1: principal amount P (a number)
Line 2: yearly rate of interest R (a number, percent)
Line 3: time period T in years (a number)

Simple Interest SI = (P * R * T) / 100
Total amount = P + SI

Print EXACTLY two lines:
Simple Interest: <SI rounded to 2 decimals>
Total Amount: <total rounded to 2 decimals>

Example
Input:
10000
7.5
3
Output:
Simple Interest: 2250.0
Total Amount: 12250.0

Note: use round(x, 2) for rounding. If SI has no fraction (like 2250.0) Python
prints 2250.0 - that exact format is expected.',
     'python', 'main.py', '# Simple Interest Calculator
P = float(input())
# TODO: read R and T, compute SI and total, print both lines
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-02-interest-calculator';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '10000
7.5
3
', 'Simple Interest: 2250.0
Total Amount: 12250.0', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '5000
10
2
', 'Simple Interest: 1000.0
Total Amount: 6000.0', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '25000
8.4
5
', 'Simple Interest: 10500.0
Total Amount: 35500.0', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1234.5
6.25
2.5
', 'Simple Interest: 192.89
Total Amount: 1427.39', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '999
3.3
1
', 'Simple Interest: 32.97
Total Amount: 1031.97', true, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '100000
2
10
', 'Simple Interest: 20000.0
Total Amount: 120000.0', true, 6);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-03-unit-converter', 'Mini Project 3: Unit Converter (km/miles & C/F)', 'Mini Projects', 'Build a unit converter that works in two modes.

Input (two lines):
Line 1: the choice - the number 1 or the number 2
Line 2: the value to convert (a number, may have decimals)

Mode 1: kilometers -> miles.  miles = km * 0.621371
Mode 2: Celsius -> Fahrenheit.  f = (c * 9/5) + 32

Print EXACTLY one line:
For mode 1: <km> km = <miles rounded to 2 decimals> miles
For mode 2: <c> degrees Celsius = <f rounded to 1 decimal place> degrees Fahrenheit

Print the input value as the user typed it (for 5 print 5, for 2.5 print 2.5).

Example
Input:
1
5
Output:
5 km = 3.11 miles

Example
Input:
2
37
Output:
37 degrees Celsius = 98.6 degrees Fahrenheit',
     'python', 'main.py', '# Unit Converter
choice = input()
# TODO: read the value, convert based on choice, print exactly one line
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-03-unit-converter';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
5
', '5 km = 3.11 miles', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
42.195
', '42.195 km = 26.22 miles', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
37
', '37 degrees Celsius = 98.6 degrees Fahrenheit', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
100
', '100 degrees Celsius = 212.0 degrees Fahrenheit', false, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
0.5
', '0.5 km = 0.31 miles', true, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
-40
', '-40 degrees Celsius = -40.0 degrees Fahrenheit', true, 6);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
36.6
', '36.6 degrees Celsius = 97.9 degrees Fahrenheit', true, 7);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-04-number-guessing', 'Mini Project 4: Number Guessing Game (fixed secret)', 'Mini Projects', 'Build a number guessing game. The secret number is read from input so the
game can be tested automatically.

Input (two lines):
Line 1: the secret number (an integer)
Line 2: space-separated guesses, e.g. 10 50 30 42

The program must respond to each guess in order:
- guess < secret  -> print: Too low!
- guess > secret  -> print: Too high!
- guess == secret -> print: Correct! You got it in <k> tries!
  (<k> = number of guesses used so far, counting this one)
  and STOP reading further guesses.

If all guesses are used without success print:
Game over! The number was <secret>

Example
Input:
42
10 50 41 42
Output:
Too low!
Too high!
Too low!
Correct! You got it in 4 tries!',
     'python', 'main.py', '# Number Guessing Game
secret = int(input())
# TODO: read the guesses line, process each guess, stop after the correct one
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-04-number-guessing';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '42
10 50 41 42
', 'Too low!
Too high!
Too low!
Correct! You got it in 4 tries!', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '7
7
', 'Correct! You got it in 1 tries!', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '100
1 2 3
', 'Too low!
Too low!
Too low!
Game over! The number was 100', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '50
25 75 50 99
', 'Too low!
Too high!
Correct! You got it in 3 tries!', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
2 3 1
', 'Too high!
Too high!
Correct! You got it in 3 tries!', true, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '9
9 9
', 'Correct! You got it in 1 tries!', true, 6);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-05-quiz-game', 'Mini Project 5: Quiz Game', 'Mini Projects', 'Build a small quiz game. The question bank is provided via input.

Input:
Line 1: N, the number of questions
Then N lines, each: question|optionA|optionB|optionC|correctLetter
  (parts separated by the | character; correctLetter is A, B or C)

The program must print each question with its options, read nothing, then at
the end print the score report:

For each question print exactly:
Q<i>. <question text>
A. <optionA>
B. <optionB>
C. <optionC>
Answer: <correctLetter>

After all questions print exactly two lines:
Total Questions: <N>
Your Score: <count of questions whose answer is A>x / <N>
  wait - no. Score counts how many correct answers are the letter A is NOT
  required. Simply print the number of questions whose correctLetter is ''A''
  as "score" is wrong. Print instead:
Your Score: <N> out of <N>
  i.e. every question is worth 1 point and the full key is shown, so the
  final line is: Your Score: <N> out of <N>

Example
Input:
2
What is 2+2?|3|4|5|B
Capital of India?|Mumbai|Delhi|Chennai|B
Output:
Q1. What is 2+2?
A. 3
B. 4
C. 5
Answer: B
Q2. Capital of India?
A. Mumbai
B. Delhi
C. Chennai
Answer: B
Total Questions: 2
Your Score: 2 out of 2

(The score line always shows the full score because the key is revealed.)',
     'python', 'main.py', '# Quiz Game
n = int(input())
# TODO: read each question line, split on |, print the formatted block
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-05-quiz-game';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
What is 2+2?|3|4|5|B
Capital of India?|Mumbai|Delhi|Chennai|B
', 'Q1. What is 2+2?
A. 3
B. 4
C. 5
Answer: B
Q2. Capital of India?
A. Mumbai
B. Delhi
C. Chennai
Answer: B
Total Questions: 2
Your Score: 2 out of 2', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
Sun rises in the?|West|East|North|B
', 'Q1. Sun rises in the?
A. West
B. East
C. North
Answer: B
Total Questions: 1
Your Score: 1 out of 1', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '3
1+1?|1|2|3|B
5-3?|2|3|4|A
10/2?|4|5|6|B
', 'Q1. 1+1?
A. 1
B. 2
C. 3
Answer: B
Q2. 5-3?
A. 2
B. 3
C. 4
Answer: A
Q3. 10/2?
A. 4
B. 5
C. 6
Answer: B
Total Questions: 3
Your Score: 3 out of 3', true, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
Python creator?|Guido|Dennis|James|A
', 'Q1. Python creator?
A. Guido
B. Dennis
C. James
Answer: A
Total Questions: 1
Your Score: 1 out of 1', true, 4);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-06-currency-denominations', 'Mini Project 6: Currency Denomination Counter', 'Mini Projects', 'An ATM counts the minimum number of notes. Indian denominations available:
500, 200, 100, 50, 20, 10, 5, 2, 1.

Input: one line with a single integer amount.
Output: for every denomination USED (in the order 500,200,100,50,20,10,5,2,1)
print exactly:
<k> x <denomination>
Then print exactly:
Total notes: <total number of notes used>

Example
Input:
683
Output:
1 x 500
1 x 100
1 x 50
1 x 20
1 x 10
1 x 2
1 x 1
Total notes: 7

Example
Input:
400
Output:
2 x 200
Total notes: 2',
     'python', 'main.py', '# Currency Denomination Counter
amount = int(input())
# TODO: greedy counting from 500 down to 1, print each used denomination
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-06-currency-denominations';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '683
', '1 x 500
1 x 100
1 x 50
1 x 20
1 x 10
1 x 2
1 x 1
Total notes: 7', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '400
', '2 x 200
Total notes: 2', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
', '1 x 1
Total notes: 1', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2889
', '5 x 500
1 x 200
1 x 100
1 x 50
1 x 20
1 x 10
1 x 5
2 x 2
Total notes: 13', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '77
', '1 x 50
1 x 20
1 x 5
1 x 2
Total notes: 4', true, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '500
', '1 x 500
Total notes: 1', true, 6);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-07-password-strength', 'Mini Project 7: Password Strength Checker', 'Mini Projects', 'Build a password strength checker.

Input: one line containing the password (it may contain spaces - read the
whole line; a password made only of spaces is not tested).

Rules (checked in this order, first match wins):
- length < 6                                        -> print: Weak
- length >= 6 AND length <= 10                      -> print: Medium
- length > 10 AND has digit AND has uppercase       -> print: Strong
- length > 10 (otherwise)                           -> print: Medium

Example
Input:
abc
Output:
Weak
Example
Input:
hello world
Output:
Medium
Example
Input:
HelloWorld123
Output:
Strong',
     'python', 'main.py', '# Password Strength Checker
password = input()
# TODO: apply the rules in order and print exactly one word
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-07-password-strength';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'abc
', 'Weak', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'hello world
', 'Medium', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'HelloWorld123
', 'Strong', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'abcdef
', 'Medium', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '12345
', 'Weak', true, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'this is a long password
', 'Medium', true, 6);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'Abcdefghij12345
', 'Strong', true, 7);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-08-electricity-bill', 'Mini Project 8: Electricity Bill Calculator', 'Mini Projects', 'Build an electricity bill calculator with slab rates.

Input: one line, units consumed (an integer).
Slab rates (charged progressively, like income tax slabs):
- first 100 units: 3.50 per unit
- next 100 units (101-200): 4.50 per unit
- above 200 units: 6.00 per unit
Fixed meter charge is always added: 50.00

Print EXACTLY one line:
Bill: <amount rounded to 2 decimals>

Example (150 units -> 100*3.50 + 50*4.50 + 50 fixed)
Input:
150
Output:
Bill: 625.0

Example
Input:
250
Output:
Bill: 1150.0

Note: round(x, 2) prints 725.0 for 725.00 - that exact format is expected.',
     'python', 'main.py', '# Electricity Bill Calculator
units = int(input())
# TODO: compute slab bill + 50 meter charge, print ''Bill: <x>''
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-08-electricity-bill';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '150
', 'Bill: 625.0', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '250
', 'Bill: 1150.0', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '50
', 'Bill: 225.0', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '0
', 'Bill: 50.0', false, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '100
', 'Bill: 400.0', false, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '201
', 'Bill: 856.0', true, 6);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '500
', 'Bill: 2650.0', true, 7);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '175
', 'Bill: 737.5', true, 8);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-09-temperature-analyzer', 'Mini Project 9: Temperature Analyzer', 'Mini Projects', 'Build a weather-log analyzer.

Input (two lines):
Line 1: N, how many temperature readings follow (integer, N >= 1)
Line 2: N readings separated by spaces (integers, Celsius)

Print EXACTLY four lines:
Highest: <max reading>
Lowest: <min reading>
Average: <average rounded to 2 decimals>
Above Average Days: <how many readings are strictly greater than the average>

Example
Input:
5
30 32 28 35 31
Output:
Highest: 35
Lowest: 28
Average: 31.2
Above Average Days: 2',
     'python', 'main.py', '# Temperature Analyzer
n = int(input())
# TODO: read the readings line, compute max, min, average, above-average count
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-09-temperature-analyzer';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '5
30 32 28 35 31
', 'Highest: 35
Lowest: 28
Average: 31.2
Above Average Days: 2', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
25
', 'Highest: 25
Lowest: 25
Average: 25.0
Above Average Days: 0', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '4
10 20 30 40
', 'Highest: 40
Lowest: 10
Average: 25.0
Above Average Days: 2', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '6
-5 0 5 -10 8 4
', 'Highest: 8
Lowest: -10
Average: 0.33
Above Average Days: 3', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '3
7 7 7
', 'Highest: 7
Lowest: 7
Average: 7.0
Above Average Days: 0', true, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '7
12 14 16 18 20 22 24
', 'Highest: 24
Lowest: 12
Average: 18.0
Above Average Days: 3', true, 6);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-10-word-counter', 'Mini Project 10: Word Counter & Analyzer', 'Mini Projects', 'Build a text analyzer for a single sentence.

Input: one line of text (may contain spaces; NOT empty).

Print EXACTLY five lines:
Words: <number of words>
Characters: <total characters including spaces>
Characters without spaces: <total minus space characters>
Longest Word: <longest word; if tie, the first occurring one>
Uppercase Count: <number of uppercase letters>

Example
Input:
I love Python programming
Output:
Words: 4
Characters: 25
Characters without spaces: 22
Longest Word: programming
Uppercase Count: 2',
     'python', 'main.py', '# Word Counter
sentence = input()
# TODO: split into words and print the five required lines
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-10-word-counter';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'I love Python programming
', 'Words: 4
Characters: 25
Characters without spaces: 22
Longest Word: programming
Uppercase Count: 2', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'hello
', 'Words: 1
Characters: 5
Characters without spaces: 5
Longest Word: hello
Uppercase Count: 0', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'A B AB
', 'Words: 3
Characters: 6
Characters without spaces: 4
Longest Word: AB
Uppercase Count: 4', true, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'Kaveri Academy teaches Python
', 'Words: 4
Characters: 29
Characters without spaces: 26
Longest Word: Academy
Uppercase Count: 3', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'aBcD eFgH
', 'Words: 2
Characters: 9
Characters without spaces: 8
Longest Word: aBcD
Uppercase Count: 4', true, 5);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-11-expense-tracker', 'Mini Project 11: Expense Tracker', 'Mini Projects', 'Build a mini expense tracker.

Input:
Line 1: N, the number of expenses
Then N lines, each: <category> <amount>   (single space separator,
amount is a number; categories are single words like food, travel)

Print EXACTLY:
Total Spent: <sum of all amounts rounded to 2>
Highest: <category with the highest total amount>
  (if tie on total, the category that reached its total first in input order
   wins - simple approach: first category in input order with max total)
Average: <total / N rounded to 2>

Example
Input:
4
food 250
travel 100
food 50
travel 200
Output:
Total Spent: 600.0
Highest: food
Average: 150.0',
     'python', 'main.py', '# Expense Tracker
n = int(input())
# TODO: read each ''category amount'' line and report totals
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-11-expense-tracker';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '4
food 250
travel 100
food 50
travel 200
', 'Total Spent: 600.0
Highest: food
Average: 150.0', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
books 499.5
', 'Total Spent: 499.5
Highest: books
Average: 499.5', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '3
a 10
b 10
c 10
', 'Total Spent: 30.0
Highest: a
Average: 10.0', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '5
x 1.25
y 2.5
x 0.75
y 2.5
z 3
', 'Total Spent: 10.0
Highest: y
Average: 2.0', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
snacks 45
movies 300
', 'Total Spent: 345.0
Highest: movies
Average: 172.5', true, 5);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-12-todo-app', 'Mini Project 12: Todo App (console)', 'Mini Projects', 'Build your own console Todo app. The tasks and commands are provided via
input so the app can be tested automatically.

Input:
Line 1: N, number of initial tasks
Then N lines, each an initial task title (single line text)
Then one line: M, number of commands
Then M lines, each a command:
  done <task number>   -> mark that task done (task numbers start at 1,
                          based on position in the CURRENT list)
  remove <task number> -> delete that task from the list
  (any other command lines are ignored)

Output: print the final list state, one line per remaining task, in order:
[<status>] <title>
where <status> is DONE or TODO.
If no tasks remain print exactly: No tasks

Example
Input:
3
Buy milk
Study Python
Call friend
3
done 1
remove 2
done 2
Output:
[DONE] Buy milk
[DONE] Call friend

Explanation: after ''done 1'' task 1 is DONE; ''remove 2'' deletes ''Study
Python''; the list is now [Buy milk(DONE), Call friend(TODO)]; ''done 2''
marks Call friend DONE.',
     'python', 'main.py', '# Todo App
tasks = []
n = int(input())
# TODO: read tasks, then commands, then print the final state
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-12-todo-app';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '3
Buy milk
Study Python
Call friend
3
done 1
remove 2
done 2
', '[DONE] Buy milk
[DONE] Call friend', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
Only task
1
remove 1
', 'No tasks', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
A
B
0
', '[TODO] A
[TODO] B', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '4
T1
T2
T3
T4
4
done 4
remove 1
done 1
done 2
', '[DONE] T2
[DONE] T3
[DONE] T4', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
X
Y
2
remove 5
done 0
', '[TODO] X
[TODO] Y', true, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '0
1
done 1
', 'No tasks', true, 6);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-13-contact-book', 'Mini Project 13: Contact Book', 'Mini Projects', 'Build a Contact Book with a dictionary.

Input:
Line 1: N, number of saved contacts
Then N lines, each: <name> <10-digit phone number>  (single space)
Then one line: Q, number of lookups
Then Q lines, each: a name to search (exact match)

For each lookup print exactly:
<name>: <phone>
or, when not found:
<name>: Not found

Example
Input:
2
Anil 9876543210
Priya 9123456780
3
Anil
Ravi
Priya
Output:
Anil: 9876543210
Ravi: Not found
Priya: 9123456780',
     'python', 'main.py', '# Contact Book
contacts = {}
n = int(input())
# TODO: save contacts, then answer lookups
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-13-contact-book';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
Anil 9876543210
Priya 9123456780
3
Anil
Ravi
Priya
', 'Anil: 9876543210
Ravi: Not found
Priya: 9123456780', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
Solo 9000000000
2
Solo
solo
', 'Solo: 9000000000
solo: Not found', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '0
1
Nobody
', 'Nobody: Not found', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '3
B 1111111111
A 2222222222
C 3333333333
3
C
A
B
', 'C: 3333333333
A: 2222222222
B: 1111111111', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
Kiran 1234567890
0
', '', true, 5);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-14-rock-paper-scissors', 'Mini Project 14: Rock Paper Scissors (fixed computer)', 'Mini Projects', 'Play Rock-Paper-Scissors against a computer whose moves are given in the
input (so the game is deterministic and testable).

Input (two lines):
Line 1: the computer''s moves, space-separated words from rock/paper/scissors
Line 2: the player''s moves, space-separated words from rock/paper/scissors
(both lines have the same count of moves)

Rules: rock beats scissors, paper beats rock, scissors beats paper,
same move is a tie.

Score: win = 1 point for the winner, tie = 1 point for each? NO - keep it
simple: each round the winner gets 1 point, a tie gives nobody a point.

Print EXACTLY three lines:
Player: <player points>
Computer: <computer points>
Result: <You win!|Computer wins!|It''s a tie!>
(the Result line compares total points; equal points -> It''s a tie!)

Example
Input:
rock paper scissors
paper scissors rock
Output:
Player: 3
Computer: 0
Result: You win!',
     'python', 'main.py', '# Rock Paper Scissors
computer_moves = input().split()
# TODO: read player moves, score each round, print the result
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-14-rock-paper-scissors';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'rock paper scissors
paper scissors rock
', 'Player: 3
Computer: 0
Result: You win!', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'rock rock rock
scissors paper rock
', 'Player: 1
Computer: 1
Result: It''s a tie!', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'paper
scissors
', 'Player: 1
Computer: 0
Result: You win!', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'rock paper
rock paper
', 'Player: 0
Computer: 0
Result: It''s a tie!', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'scissors scissors scissors
rock paper scissors
', 'Player: 1
Computer: 1
Result: It''s a tie!', true, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'rock
paper
', 'Player: 1
Computer: 0
Result: You win!', true, 6);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-15-palindrome-tool', 'Mini Project 15: Palindrome Checker', 'Mini Projects', 'Build a palindrome checker for sentences.

Input:
Line 1: N, the number of sentences
Then N lines, each a sentence (letters, digits and spaces; case must be
ignored; spaces must be ignored; punctuation is not tested)

For each sentence print exactly one line:
Yes
or
No

A sentence is a palindrome when it reads the same forwards and backwards
after ignoring case and spaces.

Example
Input:
3
Never odd or even
Hello
A man a plan a canal Panama
Output:
Yes
No
Yes',
     'python', 'main.py', '# Palindrome Checker
n = int(input())
# TODO: for each sentence, ignore case+spaces and check the palindrome
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-15-palindrome-tool';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '3
Never odd or even
Hello
A man a plan a canal Panama
', 'Yes
No
Yes', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
racecar
', 'Yes', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
Python
madam
', 'No
Yes', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
Was it a car or a cat I saw
Kaveri
', 'Yes
No', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
a
', 'Yes', true, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
Ab ba
', 'Yes', true, 6);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-16-times-table', 'Mini Project 16: Multiplication Table Generator', 'Mini Projects', 'Build a multiplication table generator.

Input: one line with the number N (integer 1..20).

Print the table of N from 1 to 10, EXACTLY in this format:
N x 1 = N1
N x 2 = N2
...
N x 10 = N10
(where N is the number and Nx is the product)

Example
Input:
7
Output:
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70',
     'python', 'main.py', '# Multiplication Table
n = int(input())
# TODO: print the table from 1 to 10
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-16-times-table';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '7
', '7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
', '1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
1 x 10 = 10', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '12
', '12 x 1 = 12
12 x 2 = 24
12 x 3 = 36
12 x 4 = 48
12 x 5 = 60
12 x 6 = 72
12 x 7 = 84
12 x 8 = 96
12 x 9 = 108
12 x 10 = 120', true, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '20
', '20 x 1 = 20
20 x 2 = 40
20 x 3 = 60
20 x 4 = 80
20 x 5 = 100
20 x 6 = 120
20 x 7 = 140
20 x 8 = 160
20 x 9 = 180
20 x 10 = 200', true, 4);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-17-grade-manager', 'Mini Project 17: Student Grade Manager', 'Mini Projects', 'Build a grade manager for one class.

Input:
Line 1: N students
Then N lines: <name> <marks>   (marks is an integer 0..100)

For each student print exactly one line:
<name>: <grade>
Grade rules:
marks >= 90 -> A+
marks >= 75 -> A
marks >= 60 -> B
marks >= 40 -> C
marks <  40 -> F

Then print exactly two class summary lines:
Class Average: <average of marks rounded to 1 decimal>
Topper: <name of the student with the highest marks (first on tie)>

Example
Input:
3
Anil 92
Priya 68
Ravi 45
Output:
Anil: A+
Priya: B
Ravi: C
Class Average: 68.3
Topper: Anil',
     'python', 'main.py', '# Grade Manager
n = int(input())
# TODO: read name+marks, print grades, then the class summary
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-17-grade-manager';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '3
Anil 92
Priya 68
Ravi 45
', 'Anil: A+
Priya: B
Ravi: C
Class Average: 68.3
Topper: Anil', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
A 100
B 0
', 'A: A+
B: F
Class Average: 50.0
Topper: A', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
Solo 75
', 'Solo: A
Class Average: 75.0
Topper: Solo', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '4
X 39
Y 40
Z 89
W 90
', 'X: F
Y: C
Z: A
W: A+
Class Average: 64.5
Topper: W', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
B 50
A 50
', 'B: C
A: C
Class Average: 50.0
Topper: B', true, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '3
P 60
Q 60
R 60
', 'P: B
Q: B
R: B
Class Average: 60.0
Topper: P', true, 6);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-18-bank-account', 'Mini Project 18: Bank Account Simulator', 'Mini Projects', 'Simulate a bank account. Start with balance 0. Process a list of
operations in order.

Input:
Line 1: N operations
Then N lines, each one of:
  deposit <amount>
  withdraw <amount>
  balance
Rules: a withdrawal is allowed only if the balance stays >= 0 after it;
otherwise print exactly: Insufficient balance
Print exactly one line per operation, in order:
  deposit -> Deposited <amount>. Balance: <balance>
  withdraw -> Withdrew <amount>. Balance: <balance>
  balance -> Balance: <balance>
Amounts are integers. Print the balance as an integer (no decimals).

Example
Input:
5
deposit 1000
withdraw 400
balance
withdraw 700
balance
Output:
Deposited 1000. Balance: 1000
Withdrew 400. Balance: 600
Balance: 600
Insufficient balance
Balance: 600',
     'python', 'main.py', '# Bank Account Simulator
balance = 0
n = int(input())
# TODO: process deposits, withdrawals and balance queries in order
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-18-bank-account';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '5
deposit 1000
withdraw 400
balance
withdraw 700
balance
', 'Deposited 1000. Balance: 1000
Withdrew 400. Balance: 600
Balance: 600
Insufficient balance
Balance: 600', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '3
deposit 500
withdraw 500
balance
', 'Deposited 500. Balance: 500
Withdrew 500. Balance: 0
Balance: 0', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
balance
', 'Balance: 0', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '4
deposit 100
withdraw 1
withdraw 99
balance
', 'Deposited 100. Balance: 100
Withdrew 1. Balance: 99
Withdrew 99. Balance: 0
Balance: 0', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '2
withdraw 1
balance
', 'Insufficient balance
Balance: 0', true, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '3
deposit 250
deposit 250
balance
', 'Deposited 250. Balance: 250
Deposited 250. Balance: 500
Balance: 500', true, 6);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-19-library-fine', 'Mini Project 19: Library Fine Calculator', 'Mini Projects', 'A library charges fines progressively:
- first 5 days late: 2 rupees per day
- next 5 days (6-10): 5 rupees per day
- after 10 days: 10 rupees per day
Returning on time (0 days late) has no fine.

Input: one line, days late (integer >= 0).

Print EXACTLY one line:
Fine: <total fine in rupees>

Examples
Input:
3
Output:
Fine: 6
Input:
8
Output:
Fine: 25        (5*2 + 3*5)
Input:
0
Output:
Fine: 0',
     'python', 'main.py', '# Library Fine Calculator
days = int(input())
# TODO: compute the progressive fine
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-19-library-fine';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '3
', 'Fine: 6', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '8
', 'Fine: 25', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '0
', 'Fine: 0', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '5
', 'Fine: 10', false, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '10
', 'Fine: 35', false, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '15
', 'Fine: 85', true, 6);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '11
', 'Fine: 45', true, 7);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, '1
', 'Fine: 2', true, 8);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('mini-20-tic-tac-toe', 'Mini Project 20: Tic-Tac-Toe Winner Checker', 'Mini Projects', 'Read a finished tic-tac-toe board and report the result.

Input: 3 lines, each with 3 characters separated by spaces.
Each character is X, O or - (dash = empty).

Print EXACTLY one line:
- X wins      (if X has three in a row)
- O wins      (if O has three in a row)
- Draw        (otherwise)
A win is any full row, column or diagonal of the same non-empty symbol.
The tests never contain both players winning at once.

Example
Input:
X O X
O X O
O X X
Output:
X wins

(X has the main diagonal positions 1,5,9.)

Example
Input:
X O X
X O O
O X X
Output:
Draw',
     'python', 'main.py', '# Tic-Tac-Toe Winner Checker
board = []
for _ in range(3):
    board.append(input().split())
# TODO: check rows, columns and diagonals, print the result
', 10, true, '83f33ce5-7ca8-4c28-af46-709e3d491285')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = 'mini-20-tic-tac-toe';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'X O X
O X O
O X X
', 'X wins', false, 1);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'X O X
X O O
O X X
', 'Draw', false, 2);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'O O X
O X X
X - -
', 'X wins', false, 3);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'X X O
X O -
O - -
', 'O wins', true, 4);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'X X X
O O -
- - -
', 'X wins', true, 5);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'X O X
O X O
X O X
', 'X wins', true, 6);
  INSERT INTO public.coding_vscode_test_cases (assignment_id, input_text, expected_output, is_hidden, position) VALUES (v_assignment_id, 'O - O
- X -
O - X
', 'Draw', true, 7);
  DELETE FROM public.coding_vscode_assignment_batches
   WHERE assignment_id = v_assignment_id AND batch_id IN ('a81f5ad9-c252-4087-b7ce-75628feb8bf0', '3778803b-1f12-4803-9768-cc0a307742f9');
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, 'a81f5ad9-c252-4087-b7ce-75628feb8bf0', true, true, now());
  INSERT INTO public.coding_vscode_assignment_batches (assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) VALUES (v_assignment_id, '3778803b-1f12-4803-9768-cc0a307742f9', true, true, now());
END $$;
COMMIT;
