#!/usr/bin/env python3
"""Convert mini_projects_seed.jsonl into idempotent seed SQL.

One command chain rebuilds the 20 Python mini projects on the linked Supabase
project. Full pipeline (run from the repo root):

  1. Validate vectors against reference solutions:
       python scripts/mini_projects.py check
  2. Emit the validated payloads (or reuse the committed JSONL as-is):
       python scripts/mini_projects.py seed > scripts/mini_projects_seed.jsonl
  3. Convert payloads to SQL:
       python scripts/mini_projects_seed_sql.py
  4. Apply to the linked production project:
       npx supabase db query --linked -f scripts/mini_projects_seed.sql

The emitted SQL is safe to re-run: assignments upsert on assignment_key,
test cases are delete+reinserted (exact hidden flags and positions), and
permanent batch releases upsert per batch. Re-running against an unchanged
database changes zero rows.

Batch IDs and created_by are the real production identifiers; update them
here if seeding a different Supabase project.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
JSONL = os.path.join(HERE, "mini_projects_seed.jsonl")
OUT = os.path.join(HERE, "mini_projects_seed.sql")

# Emit LF-only SQL even on Windows: CRLF would leak \r into string literals.
try:
    sys.stdout.reconfigure(newline="\n")
except Exception:
    pass

STAFF_ID = "83f33ce5-7ca8-4c28-af46-709e3d491285"  # faculty profile (created_by)
BATCHES = ["a81f5ad9-c252-4087-b7ce-75628feb8bf0",   # Python Batch MadanaPalle
           "3778803b-1f12-4803-9768-cc0a307742f9"]   # Office Test Batch


def esc(text: str) -> str:
    return text.replace("'", "''")


def main() -> None:
    with open(JSONL, encoding="utf-8") as fh:
        lines = [l.strip() for l in fh if l.strip() and not l.strip().startswith("--")]

    out = []
    out.append("-- Generated by scripts/mini_projects_seed_sql.py - do not edit by hand.")
    out.append("-- Rebuilds the 20 Python mini projects idempotently.")
    out.append("BEGIN;")
    for line in lines:
        p = json.loads(line)
        key = esc(p["assignment_key"])
        out.append(f"""\
DO $$
DECLARE v_assignment_id uuid;
BEGIN
  INSERT INTO public.coding_vscode_assignments
    (assignment_key, title, topic, question, language, file_name, starter_code, marks, is_published, created_by)
  VALUES
    ('{key}', '{esc(p["title"])}', '{esc(p["topic"])}', '{esc(p["question"])}',
     'python', 'main.py', '{esc(p["starter_code"])}', {p["marks"]}, true, '{STAFF_ID}')
  ON CONFLICT (assignment_key) DO UPDATE SET
    title = EXCLUDED.title, topic = EXCLUDED.topic, question = EXCLUDED.question,
    starter_code = EXCLUDED.starter_code, marks = EXCLUDED.marks,
    is_published = true, updated_at = now();

  SELECT id INTO v_assignment_id FROM public.coding_vscode_assignments
   WHERE assignment_key = '{key}';

  DELETE FROM public.coding_vscode_test_cases WHERE assignment_id = v_assignment_id;""")
        for t in p["tests"]:
            out.append(
                "  INSERT INTO public.coding_vscode_test_cases "
                "(assignment_id, input_text, expected_output, is_hidden, position) "
                f"VALUES (v_assignment_id, '{esc(t['input_text'])}', '{esc(t['expected_output'])}', "
                f"{'true' if t['is_hidden'] else 'false'}, {t['position']});")
        out.append(
            "  DELETE FROM public.coding_vscode_assignment_batches\n"
            f"   WHERE assignment_id = v_assignment_id AND batch_id IN ({', '.join(repr(b) for b in BATCHES)});")
        for b in BATCHES:
            out.append(
                "  INSERT INTO public.coding_vscode_assignment_batches "
                "(assignment_id, batch_id, is_unlocked, is_permanently_released, unlocked_at) "
                f"VALUES (v_assignment_id, '{b}', true, true, now());")
        out.append("END $$;")
    out.append("COMMIT;")

    with open(OUT, "w", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {OUT} ({len(lines)} assignments)")


if __name__ == "__main__":
    main()
