-- Store Google Calendar and Google Meet details generated by the Edge Function.
alter table public.live_sessions
  add column if not exists calendar_event_id text,
  add column if not exists meeting_id text,
  add column if not exists organizer_email text;

create index if not exists idx_live_sessions_calendar_event_id
  on public.live_sessions (calendar_event_id)
  where calendar_event_id is not null;

comment on column public.live_sessions.calendar_event_id is
  'Google Calendar event identifier created for this live session.';

comment on column public.live_sessions.meeting_id is
  'Google Meet conference identifier.';

comment on column public.live_sessions.organizer_email is
  'Google account that owns the Calendar event and Meet conference.';

notify pgrst, 'reload schema';
